In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [5]:
arr[0:6]=100

In [6]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [11]:
arr1=np.arange(50).reshape(5,10)

In [12]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
arr1[:,5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [14]:
arr1[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [15]:
#Conditional Selection

In [16]:
arr2=np.arange(20)

In [18]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
arr2[arr2>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
arr3=np.random.randint(1,100,50)

In [21]:
arr3

array([77, 27, 52, 94, 90, 16, 10, 66, 38, 54, 92, 75, 79, 89, 37, 86, 27,
        2, 55, 90, 45,  2, 28, 10, 66, 13, 32, 52, 57, 14, 24, 79, 70, 81,
       85, 70, 50,  3, 40, 58, 67, 22, 12,  4, 23, 77, 91, 67, 27, 38])

In [22]:
arr3[arr3>50]

array([77, 52, 94, 90, 66, 54, 92, 75, 79, 89, 86, 55, 90, 66, 52, 57, 79,
       70, 81, 85, 70, 58, 67, 77, 91, 67])